//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int Archive_ID { get; set; }
        public int Warranty_ID { get; set; }
        public string Location { get; set; }
        public string DocumentName { get; set; }
        public int ArchiveType_ID { get; set; }
        public byte[] Data { get; set; }
        public int CreatedBy_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
