//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.People = new HashSet<Person>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Company_ID { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public string db_name { get; set; }
        public string Local { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int CreatedBy_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
