//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int Password_ID { get; set; }
        public int Person_ID { get; set; }
        public byte[] HashValue { get; set; }
        public int InsertionOrder { get; set; }
        public int Try { get; set; }
        public int AccessesCount { get; set; }
        public Nullable<System.DateTime> LastAccesses { get; set; }
        public int Status_ID { get; set; }
        public int CreatedBy_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Person Person { get; set; }
    }
}
