//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvisionHeader
    {
        public int ProvisionHeader_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string ProvisionType { get; set; }
        public int Secuence { get; set; }
        public string Comment { get; set; }
        public int Currency_ID { get; set; }
        public int ProvisionStatus_ID { get; set; }
        public int CreatedBy_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
