//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int User_ID { get; set; }
        public int Person_ID { get; set; }
        public string Name { get; set; }
        public int Access_ID { get; set; }
        public int UserStatus_ID { get; set; }
        public int CreatedBy_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Detail Detail { get; set; }
        public virtual Detail Detail1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
