//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Tab
    {
        public int Tab_ID { get; set; }
        public string Html_ID { get; set; }
        public string TabName { get; set; }
        public int Order { get; set; }
    }
}
