//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DocumentTipe
    {
        public int DocumentTypeId { get; set; }
        public string DocumentType { get; set; }
    }
}
